name: login_register_screen
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.8.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.6595

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

